# Generated by Django 3.2.9 on 2021-12-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Ab', 'Ab'), ('G#', 'G#'), ('A#', 'A#'), ('Bb', 'Bb'), ('C#', 'C#'), ('Db', 'Db'), ('D#', 'D#'), ('Eb', 'Eb'), ('F#', 'F#'), ('Gb', 'Gb')], max_length=2)),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FretboardLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('fret', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretboard_exercises.note')),
            ],
        ),
    ]
