# Generated by Django 3.2.9 on 2021-12-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretboard_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('G#/Ab', 'G#/Ab'), ('A#/Bb', 'A#/Bb'), ('C#/Db', 'C#/Db'), ('D#/Eb', 'D#/Eb'), ('F#/Gb', 'F#/Gb')], max_length=5),
        ),
    ]
