# Generated by Django 3.2.9 on 2021-12-29 05:40

from django.db import migrations
from .helpers.fret_data_migration_helper import load_fretboard_data, ParametrizedRunPython


class Migration(migrations.Migration):

    dependencies = [
        ('fretboard_exercises', '0003_rename_note_note_name'),
        ('fretboard_exercises', '0005_guitarfretboardlocation_delete_fretboardlocation'),
    ]

    operations = [
        ParametrizedRunPython(load_fretboard_data,
                              context={
                                  'seed_data_path': "guitar_fretboard_seed_data.csv",
                                  'fretboardlocation_model': 'GuitarFretboardLocation'
                              }),
    ]
