# Generated by Django 3.2.9 on 2021-12-29 05:40

from django.db import migrations
from django.core.exceptions import ValidationError
import csv


# TODO figure out how to populate data for FretboardLocation. Interweave with the below or do it separately?
# TODO should I add more notes now rather than having to rewrite this later?
#  How will new notes be added later (e.g. bass, beyond 12th fret)
def load_fretboard_data(apps, schema_editor):
    Note = apps.get_model('fretboard_exercises', 'Note')
    filepath = r"C:\Users\Daniel\PycharmProjects\fretboard_mastery\guitar_exercises\fretboard_data.csv"
    with open(filepath, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        i = 0
        note = 0
        frequency = 1
        for row in reader:
            row[note] = row[note].replace(f"{int((i + 3)/12 + 2)}", '')
            if len(row[note]) > 1:
                row[note] = row[note].replace('\xa0', '')
            print(f"{'0' if i < 10 else ''}{i}. {row[note]}{(7 - len(row[note]))*' '}{row[frequency]}")
            try:
                new_note = Note(note=row[note], frequency=row[frequency])
                new_note.full_clean()
                new_note.save()
            except ValidationError as e:
                print('Validation error!')
                # TODO what do do here?
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('fretboard_exercises', '0003_rename_note_note_name'),
    ]

    operations = [
        migrations.RunPython(load_fretboard_data),
    ]
