# Generated by Django 4.0 on 2022-01-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fretboard_exercises', '0003_rename_note_note_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarFretboardLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('fret', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)])),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretboard_exercises.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FretboardLocation',
        ),
    ]
